### ISSUE TITLE
no-bounce disables links in iOS

### ISSUE THREAD

**Issue by dhelbig** [timbartsch/no-bounce#2]
This tool works great with the bouncing issue, but somehow, if the script is running, links won't work anymore (only in iOS).

**Comment by timbartsch** [comment]
Thanks for your feedback!

Please try to run noBounce with `preventDefault: false` like:

    noBounce.init({preventDefault: false, animate: true});


If `preventDefault` is enabled the default  behavior of the touchevent gets disabled. The default  behavior of touch events on links is opening them. That's why opening links doesn't work with `preventDefault: true`.

**Comment by dhelbig** [comment]
Thanks for the response. I tried to change this setting for ```preventDefault:``` but then the function didn't work properly.

**Comment by timbartsch** [comment]
Can you further explain what "didn't work properly" means?
Did you get any js errors or did the browser start bouncing again?

**Comment by dhelbig** [comment]
Sorry, yes of course. 
As I said, the problem is just iOS (didn't checked Android).

I got a horizontal-scrolling page with a fixed height.
While scrolling to the left or the right, the browser started bouncing, so I installed nobounce.js.

on ```preventDefault: true``` the links didn't work anymore.
on ```preventDefault: false``` the stage was bouncing again and started to flicker.

I uploaded the two versions for you to see:
http://dennishelbig.com/downright/true.html
http://dennishelbig.com/downright/false.html

(links are the filters on the bottom or the heart for menu)

**Comment by timbartsch** [comment]
Thanks for this comprehensive explanation.
I think that behavior is a bug in noBounce that is easy to fix.
I will update the repo this evening.

**Comment by timbartsch** [comment]
I fixed the bug and removed the `preventDefault` option from the noBounce.js init call.
So the new version with the following init call should work now for you:

    noBounce.init({animate: true});


But disabling the bounce effect directly in the webview (if you have access to it) is always the best option.
